version: '3.7'

services:


  db:
    container_name: datascout_db
    image: "postgres:14.2"
    environment:
      POSTGRES_USER: datascout
      POSTGRES_PASSWORD: datascout
      POSTGRES_DB: datascout_db
    networks:
      - datascout
    profiles:
      - db
      - dev
      - deploy

  fast-api:
    container_name: datascout_fastapi
    build:
      dockerfile: Dockerfile
      context: ./python
    volumes:
      - ./python/app:/app
    networks:
      - datascout
    profiles:
      - dev
      - deploy

  nginx:
    container_name: datascout_nginx
    build:
      dockerfile: Dockerfile
      context: ./datascout-front
    ports:
      - "91:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./storage:/storage
    networks:
      - datascout
    profiles:
      - deploy

  spring-boot:
    container_name: datascout_spring-boot
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./storage:/storage
    environment:
      DATASOURCE_URL: "jdbc:postgresql://db:5432/datascout_db"
      FASTAPI_URL: "http://fast-api:3333"
    networks:
      - datascout
    profiles:
      - deploy

networks:
  datascout:
