version: '3.7'

services:

  db:
    container_name: datascout_db
    image: "postgres:14.2"
    environment:
      POSTGRES_USER: datascout
      POSTGRES_PASSWORD: datascout
      POSTGRES_DB: datascout_db
    ports:
      - "9432:5432"
    networks:
      - datascout
    profiles:
      - db
      - dev

  fast-api:
    container_name: datascout_fastapi
    build:
      dockerfile: Dockerfile
      context: ./python
    ports:
      - "3333:3333"
    volumes:
      - ./python/app:/app
    networks:
      - datascout
    profiles:
      - dev

  nginx:
    container_name: datascout_nginx
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - datascout
    profiles:
      - dev

  spring-boot:
    container_name: datascout_spring-boot
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8081:8080"
    # volumes:
    #   - ./backend:/app/src
    environment:
      DATASOURCE_URL: "jdbc:postgresql://db:5432/datascout_db"
      FASTAPI_URL: "http://fast-api:3333"
    networks:
      - datascout
    profiles:
      - dev


  pgadmin:
    container_name: pgadmin4-datascout
    image: dpage/pgadmin4
    environment:
      PGADMIN_DISABLE_POSTFIX: "True"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "40"
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - "50001:80"
    profiles:
      - dev
    networks:
      - datascout

networks:
  datascout:
